### ISSUE TITLE
Could not start up, pythonnet error - Windows Python

### ISSUE THREAD

**Issue by Zafford** [quadrismegistus/mastotron#16]
Different error message than others:  [pywebview] pythonnet cannot be loaded ( raise WebViewException('You must have pythonnet installed in order to use pywebview.')) But if I istall pythonnet it says it is already installed: "Requirement already satisfied: pythonnet in d:\tools\python\lib\site-packages (3.0.1)"

**Comment by quadrismegistus** [comment]
Bummer -- are you able to start it up using [the new windows instructions?](https://github.com/mastotron/mastotron#windows) The windowing issues are breaking for both linux and windows which will time to fix, but it's not much more complicated to run it in background mode and then use your own browser to view it.

**Comment by rmdes** [comment]
I have tested it now with the latest Windows instruction and I can't get past the point where I insert my mastodon handle, after that nothing happens. It's running from the miniconda shell

Traceback from the miniconda shell : 

Traceback (most recent call last):
  File "C:\Users\rick\miniconda3\lib\site-packages\mastotron\gui\app.py", line 167, in set_acct_name
    logmsg('Please enter activation code')
  File "C:\Users\rick\miniconda3\lib\site-packages\mastotron\gui\app.py", line 54, in logmsg
    emitt('logmsg',' '.join(str(xx) for xx in x))
  File "C:\Users\rick\miniconda3\lib\site-packages\mastotron\gui\app.py", line 61, in emitt
    socketio.emit(key,val,*vals,broadcast=broadcast,**opts)
  File "C:\Users\rick\miniconda3\Lib\site-packages\flask_socketio\__init__.py", line 462, in emit
    self.server.emit(event, *args, namespace=namespace, to=to,
TypeError: Server.emit() got an unexpected keyword argument 'broadcast'

During handling of the above exception, another exception occurred:

```
Traceback (most recent call last):
  File "src\\gevent\\greenlet.py", line 908, in gevent._gevent_cgreenlet.Greenlet.run
  File "C:\Users\rick\miniconda3\Lib\site-packages\socketio\server.py", line 733, in _handle_event_internal
    r = server._trigger_event(data[0], namespace, sid, *data[1:])
  File "C:\Users\rick\miniconda3\Lib\site-packages\socketio\server.py", line 758, in _trigger_event
    return self.handlers[namespace][event](*args)
  File "C:\Users\rick\miniconda3\Lib\site-packages\flask_socketio\__init__.py", line 282, in _handler
    return self._handle_event(handler, message, namespace, sid,
  File "C:\Users\rick\miniconda3\Lib\site-packages\flask_socketio\__init__.py", line 828, in _handle_event
    ret = handler(*args)
  File "C:\Users\rick\miniconda3\lib\site-packages\mastotron\gui\app.py", line 171, in set_acct_name
    emitt('server_not_giving_code', {'server':server, 'acct':acct})
  File "C:\Users\rick\miniconda3\lib\site-packages\mastotron\gui\app.py", line 61, in emitt
    socketio.emit(key,val,*vals,broadcast=broadcast,**opts)
  File "C:\Users\rick\miniconda3\Lib\site-packages\flask_socketio\__init__.py", line 462, in emit
    self.server.emit(event, *args, namespace=namespace, to=to,
TypeError: Server.emit() got an unexpected keyword argument 'broadcast'
2023-04-01T17:31:51Z <Thread at 0x12ce1c6f1a0: <bound method Server._handle_event_internal of <socketio.server.Server object at 0x0000012CE1CBBCD0>>(<socketio.server.Server object at 0x0000012CE1CBBC, 'kh0kmq69HOjmHSLMAAAD', 'QGBPslNbw_6A0H6nAAAC', ['set_acct_name', {'acct': 'rmdes@mstdn.social'}], '/', None)> failed with TypeError
```

Will try later on my linux box
